#Minecraft server properties
#Mon Oct 05 19:29:16 BRT 2026
spawn-protection=16
max-tick-time=60000
accepts-transfers=false
query.port=25565
generator-settings=
sync-chunk-writes=true
force-gamemode=false
allow-nether=true
enforce-whitelist=false
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
text-filtering-config=
difficulty=1
spawn-monsters=true
broadcast-rcon-to-ops=true
op-permission-level=4
simulation-distance=5
pvp=true
entity-broadcast-range-percentage=100
snooper-enabled=true
level-type=minecraft\:normal
hardcore=false
enable-status=true
enable-command-block=true
max-players=20
network-compression-threshold=512
resource-pack-sha1=
max-world-size=29999984
function-permission-level=2
rcon.port=25575
server-port=25565
server-ip=
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=6
resource-pack=
spawn-animals=true
white-list=false
rcon.password=SGItosSaveSecretPass2026\!
generate-structures=true
max-build-height=256
enforce-secure-profile=true
online-mode=false
level-seed=
use-native-transport=true
prevent-proxy-connections=false
enable-jmx-monitoring=false
hide-online-players=false
motd=\u00A76\u00A7lMinecraft dos SGItos\u00A7r \u00A77-\u00A7r \u00A7bServidor Oficial\n\u00A7e\u2728 Entre e divirta-se\!
rate-limit=0
enable-rcon=true
